[window]
opacity = 0.92
padding = { x = 10, y = 10 }

[font]
size = 13.5

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[font.bold]
family = "UbuntuMono Nerd Font"
style = "Bold"

[font.italic]
family = "UbuntuMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "UbuntuMono Nerd Font"
style = "Bold Italic"

[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"

[colors.cursor]
text = "#1e1e2e"
cursor = "#f5e0dc"

[colors.vi_mode_cursor]
text = "#1e1e2e"
cursor = "#b4befe"

[colors.selection]
text = "#1e1e2e"
background = "#f5e0dc"

[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#94e2d5"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#94e2d5"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"
